export default [
  {
    name: "ID",
    align: "left",
    label: "ID",
    field: "ID",
    sortable: true,
    form: false,
  },
  {
    name: "NOME",
    align: "left",
    label: "Nome",
    field: "NOME",
    sortable: true,
    form: true,
    type: "text",
  },
  {
    name: "CELULAR",
    align: "left",
    label: "Celular",
    field: "CELULAR",
    sortable: true,
    form: true,
    type: "mobile",
  },
  {
    name: "TELEFONE",
    align: "left",
    label: "Telefone",
    field: "TELEFONE",
    sortable: true,
    form: true,
    type: "phone",
  },
  {
    name: "EMAIL",
    align: "left",
    label: "E-mail",
    field: "EMAIL",
    sortable: true,
    form: true,
    type: "email",
  },
  {
    name: "ATIVO",
    align: "left",
    label: "Status",
    field: "ATIVO",
    sortable: true,
    form: true,
    type: "checkbox",
  },
  {
    name: "ACTIONS",
    align: "left",
    label: "Ações",
    field: "ACTIONS",
    sortable: false,
    form: false,
  },
];
