export default [
  {
    name: "ID",
    align: "left",
    label: "ID",
    field: "ID",
    sortable: true,
    type: "text",
    form: false,
  },
  {
    name: "NOME",
    align: "left",
    label: "Nome",
    field: "NOME",
    sortable: true,
    type: "text",
    form: true,
  },
  {
    name: "TELEFONE",
    align: "left",
    label: "Telefone",
    field: "TELEFONE",
    sortable: true,
    type: "phone",
    form: true,
  },
  {
    name: "EMAIL",
    align: "left",
    label: "E-mail",
    field: "EMAIL",
    sortable: true,
    type: "email",
    form: true,
  },

  {
    name: "ATIVO",
    align: "left",
    label: "Status",
    field: "ATIVO",
    sortable: true,
    type: "checkbox",
    form: true,
  },
  {
    name: "ACTIONS",
    align: "left",
    label: "Ações",
    field: "ACTIONS",
    sortable: false,
    type: "text",
    form: false,
  },
];
