export default [
  {
    name: "ID",
    align: "left",
    label: "ID",
    field: "ID",
    sortable: true,
    form: false,
  },
  {
    name: "NOME",
    align: "left",
    label: "Nome",
    field: "NOME",
    sortable: true,
    form: false,
    type: "text",
  },
  {
    name: "QUANTIDADE",
    align: "left",
    label: "Qtde",
    field: "QUANTIDADE",
    sortable: true,
    form: false,
    type: "number",
  },
  {
    name: "VALOR",
    align: "left",
    label: "Valor R$ R$",
    field: "VALOR",
    sortable: true,
    form: false,
    type: "number",
  },
  {
    name: "TOTAL",
    align: "left",
    label: "Total R$",
    field: "TOTAL",
    sortable: true,
    form: true,
    type: "select",
  },
  {
    name: "ACTIONS",
    align: "left",
    label: "Ações",
    field: "ACTIONS",
    sortable: false,
    form: false,
  },
];
