export default [
  {
    name: "ID",
    align: "left",
    label: "ID",
    field: "ID",
    sortable: true,
    form: false,
  },
  {
    name: "ID_CLIENTE",
    align: "left",
    label: "ID",
    field: "ID_CLIENTE",
    sortable: true,
    form: false,
    type: "text",
  },
  {
    name: "NOME",
    align: "left",
    label: "Cliente",
    field: "NOME",
    sortable: true,
    form: false,
    type: "number",
  },
  {
    name: "TOTAL",
    align: "left",
    label: "Total R$",
    field: "TOTAL",
    sortable: true,
    form: false,
    type: "number",
  },
  {
    name: "TIPO_PAGAMENTO",
    align: "left",
    label: "Pagamento",
    field: "TIPO_PAGAMENTO",
    sortable: true,
    form: true,
    type: "select",
  },
  {
    name: "PAGO",
    align: "left",
    label: "Status",
    field: "PAGO",
    sortable: true,
    form: true,
    type: "checkbox",
  },
  {
    name: "ACTIONS",
    align: "left",
    label: "Ações",
    field: "ACTIONS",
    sortable: false,
    form: false,
  },
];
